rules:
  # Allowlist trusted actions
  forbidden-uses:
    config:
      allow: # Get approval from your manager before adding actions to this list.
        - canonical/*
        - actions/*
        - docker/login-action
        - tiobe/tics-github-action
  unpinned-uses:
    config:
      policies:
        canonical/*: ref-pin
        actions/*: ref-pin
        docker/login-action: ref-pin
        tiobe/tics-github-action: ref-pin