rules:
  # Allowlist trusted actions and pre-commit repos.
  forbidden-uses:
    config:
      allow: # Get approval from your manager before adding actions to this list.
        - canonical/*
        - actions/*
        - docker/login-action
        - tiobe/tics-github-action
        - python-poetry/poetry
        - pre-commit/pre-commit-hooks
        - astral-sh/ruff-pre-commit
        - codespell-project/codespell
        - rhysd/actionlint
  unpinned-uses:
    config:
      policies:
        canonical/*: ref-pin
        actions/*: ref-pin
        docker/login-action: ref-pin
        tiobe/tics-github-action: ref-pin