# https://canonical-charm-refresh.readthedocs-hosted.com/latest/add-to-charm/refresh-versions-toml/

charm_major = 1
workload = "2.19.2"

[snap]
name = "opensearch-dashboards"

[snap.revisions]

# amd64
x86_64 = "41"
