# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
no_package = True
env_list = lint

[vars]
application = opensearch_dashboards 
src_path = {tox_root}
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}

[testenv]
allowlist_externals =
    /bin/bash
    poetry
set_env =
    PYTHONPATH = {[vars]src_path}:{tox_root}/lib
    PY_COLORS = 1
    PIP_IGNORE_INSTALLED = 1
    POETRY_INSTALLER_PARALLEL = false
pass_env =
    poetry

[testenv:format]
description = Apply coding style standards to code
skip_install = true
commands_pre =
    poetry install --only format --no-root
commands =
    poetry lock
    poetry run ruff check --config {tox_root}/pyproject.toml --fix {[vars]all_path}
    poetry run ruff format --config {tox_root}/pyproject.toml {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
skip_install = true
commands_pre =
    poetry install --only lint --no-root
commands =
    poetry check --lock
    poetry run codespell --toml {tox_root}/pyproject.toml {[vars]all_path}
    poetry run ruff check --config {tox_root}/pyproject.toml {[vars]all_path}
    poetry run ruff format --check --config {tox_root}/pyproject.toml --diff {[vars]all_path}

[testenv:integration]
description = Run all integration tests
pass_env =
    CI
    CHARM_UBUNTU_BASE
    SUBSTRATE
    TEST_TLS
    TEST_TRAEFIK
    TRANSFER_TRAEFIK_CA
allowlist_externals =
    {[testenv]allowlist_externals}
    poetry
commands_pre =
    poetry install --only integration
commands =
    poetry run pytest -vv --tb native --log-cli-level=INFO {posargs}
