# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".gitignore"
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
    outputs:
      artifact-prefix:
        description: build_charm.yaml `artifact-prefix` output
        value: ${{ jobs.build.outputs.artifact-prefix }}
    secrets:
      CHARMHUB_TOKEN:
        required: false

jobs:
  lint:
    name: Lint
    uses: canonical/data-platform-workflows/.github/workflows/lint_workflows.yaml@v50.0.0
    permissions:
      contents: read

  promtool:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      # prometheus snap includes promtool
      - name: Install prometheus snap
        run: sudo snap install prometheus

      - name: Check validity of prometheus alert rules for K8s
        run: |
          promtool check rules kubernetes/src/alert_rules/prometheus/*.yaml

      - name: Check validity of prometheus alert rules for VM
        run: |
          promtool check rules machines/src/alert_rules/prometheus/*.yaml

  terraform-test:
    name: Terraform - Lint and Simple Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Terraform
        run: sudo snap install terraform --classic

      - name: lint charm module
        run: |
          pushd ./terraform
          terraform init && terraform fmt && terraform validate
          popd
      - name: run checks - prepare
        run: |
          sudo snap install juju --channel=3.6 --classic
      - name: LXD setup
        run: |
          if snap list lxd >/dev/null 2>&1; then
            sudo snap refresh lxd --channel=latest/stable
          else
            sudo snap install lxd --channel=latest/stable
          fi
          sudo adduser "$USER" 'lxd'
          # `newgrp` does not work in GitHub Actions; use `sg` instead
          sg 'lxd' -c "lxd waitready"
          sg 'lxd' -c "lxd init --auto"
          sg 'lxd' -c "lxc network set lxdbr0 ipv6.address none"
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT
      - name: Juju setup
        run: |
          sg 'lxd' -c "juju bootstrap 'localhost' --config model-logs-size=10G"
          juju model-defaults logging-config='<root>=INFO; unit=DEBUG'
          juju add-model test
      - name: Terraform deploy
        run: |
          MODEL_UUID=$(juju show-model test | grep "model-uuid" | awk '{split($0, a, ": "); print a[2]}')
          pushd ./terraform
          terraform apply -var="model_uuid=$MODEL_UUID" -auto-approve
          popd
      - name: Wait for model and applications
        run: |
          juju wait-for application opensearch-dashboards -m test --query='status=="blocked"'
          juju wait-for model test --query='life=="alive" && status=="available"'

  build:
    strategy:
      matrix:
        path:
          - kubernetes
          - machines
          - tests/integration/dashboards_application_charm
          - tests/integration/dashboards_tester_charm
    name: Build charm | ${{ matrix.path }}
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v50.0.0
    with:
      cache: false
      path-to-charm-directory: ${{ matrix.path }}
    permissions:
      contents: read

  integration-test:
    name: Integration test charm
    needs:
      - lint
      - build
    uses: ./.github/workflows/integration_test.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    permissions:
      contents: write # Needed for Allure Report